Product-Review-System/Models/AddProduct.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Product_Review_System.Models
{
    public class addProduct
    {
        [DisplayName("Product id")]
        public int id { get; set; }

        [DisplayName("Name")]
        public string name { get; set; }

        [DisplayName("Price")]
        public int price { get; set; }

        [DisplayName("Description")]
        public string description { get; set; }

        [DisplayName("Category id")]
        public int category_id { get; set; }

        public Category Category { get; set; }

        [DisplayName("Image")]
        public String image { get; set; }


    }
}

Product-Review-System/Controllers/addProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Product_Review_System.Models;
using WebApplication4.Models;
using System.IO;

namespace Product_Review_System.Controllers
{
    public class addProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: addProducts
        public ActionResult Index()
        {
            var addProducts = db.AddProducts.Include(a => a.Category);
            return View(addProducts.ToList());
        }

        // GET: addProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            addProduct addProduct = db.AddProducts.Find(id);
            if (addProduct == null)
            {
                return HttpNotFound();
            }
            return View(addProduct);
        }

        // GET: addProducts/Create
        public ActionResult Create()
        {
            ViewBag.category_id = new SelectList(db.Categories, "category_id", "name");
            return View();
        }

        // POST: addProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(addProduct addProduct, HttpPostedFileBase upload)
        {

            if (ModelState.IsValid)
            {
                string path = "";
                if (upload.FileName.Length > 0)
                {
                    path = "~/Uploads/" + Path.GetFileName(upload.FileName);
                    upload.SaveAs(Server.MapPath(path));
                }
                addProduct.image = path;
                var categoryindb = db.Categories.Single(c => c.category_id == addProduct.category_id);
                categoryindb.no_of_products++;
                db.AddProducts.Add(addProduct);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return Content("Done");
        }

        public ActionResult SearchProduct(string search)
        {
            return View(db.AddProducts.Where(x => x.name.Contains(search) || search == null).ToList());

        }


        // GET: addProducts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            addProduct addProduct = db.AddProducts.Find(id);
            if (addProduct == null)
            {
                return HttpNotFound();
            }
            ViewBag.category_id = new SelectList(db.Categories, "category_id", "name", addProduct.category_id);
            return View(addProduct);
        }

        // POST: addProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,price,description,category_id,image")] addProduct addProduct)
        {
            if (ModelState.IsValid)
            {
                db.Entry(addProduct).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.category_id = new SelectList(db.Categories, "category_id", "name", addProduct.category_id);
            return View(addProduct);
        }

        // GET: addProducts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            addProduct addProduct = db.AddProducts.Find(id);
            if (addProduct == null)
            {
                return HttpNotFound();
            }
            return View(addProduct);
        }

        // POST: addProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            addProduct addProduct = db.AddProducts.Find(id);
            db.AddProducts.Remove(addProduct);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Product-Review-System/Views/AddProducts/Create.cshtml
@model Product_Review_System.Models.addProduct

@{
    ViewBag.Title = "Add product";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h1>Add Product</h1>

@using (Html.BeginForm("Create", "AddProducts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, "category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload"/>
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" style="background-color:black" class="btn btn-primary btn-lg" />
            </div>
        </div>
    </div>

    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}

Product-Review-System/Views/AddProducts/Delete.cshtml
@model Product_Review_System.Models.addProduct

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        

        <dt>
           Product Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img src="@Url.Content(Model.image)" alt="@Model.name" />
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" style="background-color:black" class="btn btn-primary btn-lg" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Product-Review-System/Views/AddProducts/Details.cshtml
@model Product_Review_System.Models.addProduct

@{
    ViewBag.Title = "View Product";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}




<h2>View Product</h2>


<div>
    <dl class="dl-horizontal">
        <dd>
            @Html.DisplayFor(model => model.Category.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img src="@Url.Content(Model.image)" alt="@Model.name" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Product-Review-System/Views/AddProducts/Edit.cshtml
@model Product_Review_System.Models.addProduct

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Edit Product</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, "category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" />
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" style="background-color:black" class="btn btn-primary btn-lg" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Product-Review-System/Views/AddProducts/Index.cshtml
@model IEnumerable<Product_Review_System.Models.addProduct>

@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


<p>
    <h3>@Html.ActionLink("Create New Product", "Create")</h3>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.price)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.description)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.image)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Category.name)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
        @Html.ActionLink("View product", "Details", new { id = item.id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.id })
  
        
    </td>
</tr>
}

</table>

Product-Review-System/Views/AddProducts/SearchProduct.cshtml
@model IEnumerable<Product_Review_System.Models.addProduct>
@{
    ViewBag.Title = "SearchProduct";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>SearchProduct</h2>

<p>
    @using (Html.BeginForm("SearchProduct", "addProducts", FormMethod.Post))

    {
        @Html.TextBox("search")
        <input style="background-color:black" class="btn btn-primary btn-lg" type="submit" value="search" />
    
}

    <table class="table table-striped">
        <thead>
            <tr>
                <th> name </th>
                <th> price </th>
                <th> description </th>
                <th> category </th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="3" style="color:red">
                        No Match Any Document
                    </td>
                </tr>
            }
            else
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.name</td>
                        <td>@item.price</td>
                        <td>@item.description</td>
                        <td>@item.category_id</td>
                    </tr>
                }
            }
            }
        </tbody>
    </table>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>